import Navbar from '@/components/Navbar';
import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import { ShoppingCartProvider } from '@/context/ShoppingCartContext';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ShoppingCartProvider>
        <Navbar/>
        {children}
        </ShoppingCartProvider>
      </body>
    </html>
  )
}
